
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:accountsdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  logging:
    level:
      org.springframework: INFO
      com.yuexin: INFO