
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: {cipher}b3978ed2796917f55b0afee19be2d0df65b822b8f2d7c9c5c09933bda6e6e4d2
    password: " "
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
